In [1]:
import numpy as np

In [2]:
# create a 1D NumPy array
a = np.array([1, 2, 3, 4, 5])

# print the array
print(a)

# access elements of the array
print(a[0])
print(a[2:4])

# perform operations on the array
print(a + 2)
print(a * 3)
print(np.sqrt(a))

[1 2 3 4 5]
1
[3 4]
[3 4 5 6 7]
[ 3  6  9 12 15]
[1.         1.41421356 1.73205081 2.         2.23606798]


In [3]:
# create a 2D NumPy array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# print the array
print(b)

# access elements of the array
print(b[0, 1])
print(b[1:3, 0:2])

# perform operations on the array
print(b + 2)
print(b * 3)
print(np.sqrt(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[[4 5]
 [7 8]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [4]:
# create a NumPy array
c = np.array([1, 2, 3, 4, 5])

# calculate the mean of the array
print(np.mean(c))

# calculate the standard deviation of the array
print(np.std(c))

# calculate the sum of the array
print(np.sum(c))

# calculate the maximum and minimum values of the array
print(np.max(c))
print(np.min(c))

3.0
1.4142135623730951
15
5
1


In [5]:
array3= np.array([["W","o","a","!"],["You","Are","Crazy","today!"]])

In [6]:
print(array3)

[['W' 'o' 'a' '!']
 ['You' 'Are' 'Crazy' 'today!']]


In [7]:
array3.shape

(2, 4)

In [8]:
zeros= np.zeros((2,6))

In [9]:
print(zeros)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [10]:
zeros[0,0]=2
print(zeros)

[[2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [11]:
ones = np.ones((8,5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
